{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) -}}
{{- if or (not .Values.auth.username) (not .Values.auth.password) -}}
{{- fail "auth.username and auth.password are required when auth.enabled=true and auth.existingSecret is empty" -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "esphome-device-builder.authSecretName" . }}
  labels:
    {{- include "esphome-device-builder.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.usernameKey }}: {{ .Values.auth.username | quote }}
  {{ .Values.auth.passwordKey }}: {{ .Values.auth.password | quote }}
{{- end }}
